import Head from 'next/head';
import Pagination from './components/common/Pagination';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <h1>my next project</h1>
        <hr />
        <p>hello world</p>
      </header>
      <div>
        <Pagination />
      </div>
      <style jsx>
        {`
          h1 {
            font-size: 32px;
          }

          p {
            color: gray;
          }
        `}
      </style>
    </>
  );
}
