import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <header>
        <h1>my next project</h1>
        <hr />
        요즘 유행하는 프론트엔드 기술 스택
        <ul>
          <li>- next.js (react SSR framework)</li>
          <li>- typescript</li>
          <li>- react-query</li>
          <li>- jotai</li>
          <li>- styled-component</li>
        </ul>
        <br/>
        DB 대용: gogole spread sheet api
      </header>
      <style jsx>
        {`
          h1 {
            font-size: 32px;
          }

          p {
            color: gray;
          }
        `}
      </style>
    </>
  );
}
